global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'saeta-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          app: 'saeta-backend-v2'
          environment: 'development'
